name: Lint

concurrency:
  # for PR's cancel the running task, if another commit is pushed
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  # build on PR and push-to-main. This works for short-lived branches, and saves
  # CPU cycles on duplicated tests.
  # For long-lived branches that diverge, you'll want to run on all pushes, not
  # just on push-to-main.
  pull_request: {}
  push:
    branches:
    - master


jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: luarocks/gh-actions-lua@816ec4c55af2f6dcb9dfcba372d93dd1fb5fa8f2
        with:
          luaVersion: "5.4"

      - uses: luarocks/gh-actions-luarocks@e42874645a111d78a858c3dba7530bdd707b21a4
        with:
          luaRocksVersion: "3.13.0"

      - name: dependencies
        run: |
          luarocks install luacheck

      - name: lint
        run: |
          make check
